# DEEP LEARNING
## Pytorch Basic

In [27]:
import torch

In [28]:
torch.cuda.is_available()

False

Dataset with pytorch

In [29]:
import torch
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

df = pd.read_csv('Iris.csv')
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [30]:
df.shape

(150, 6)

In [31]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
le = LabelEncoder()
X = df.drop(['Species'], axis=1).values
y = le.fit_transform(df['Species'].values)

# Chia dữ liệu với test size = 20%
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train = torch.FloatTensor(X_train)
X_test = torch.FloatTensor(X_test)
y_train = torch.LongTensor(y_train).reshape(-1, 1)
y_test = torch.LongTensor(y_test).reshape(-1, 1)

In [32]:
len(y_train)

120

In [33]:
labels, counts = y_train.unique(return_counts=True)
print(labels, counts)


tensor([0, 1, 2]) tensor([40, 41, 39])


In [ ]:
# Tính đạo hàm bằng pytorch

# Cho y = 2x^4 + x^3 + 3x^2 + 5x + 1

# Tính y'

import torch
x = torch.tensor(2.0, requires_grad=True)
print(x)
print(x.grad)  


tensor(2., requires_grad=True)
None


In [26]:
# Định nghĩa hàm
y = 2*x**4 + x**3 + 3*x**2 + 5*x + 1
print(y)

tensor(63., grad_fn=<AddBackward0>)


In [27]:
y.grad_fn

In [28]:
# Thực hiện lan truyền ngược và tính toán các gradient

y.backward()

In [29]:
x.grad

tensor(93.)

# BTVN
## Bài 1
Cho y = 5x^5 + 6x^3 - 3x + 1

Cho biết độ dốc của đa thức trên ở điểm nào


In [1]:
import torch

x = torch.tensor(1.0, requires_grad=True)

y = 5*x**5 + 6*x**3 - 3*x + 1

y.backward()

print(f"Hàm số: y = 5x^5 + 6x^3 - 3x + 1")
print(f"Độ dốc của hàm số tại x = {x.item()} là: {x.grad.item()}")


Hàm số: y = 5x^5 + 6x^3 - 3x + 1
Độ dốc của hàm số tại x = 1.0 là: 40.0


## Bài 2
Tạo một tensor ban đầu có giá trị là 2

Định nghĩa hàm số và tính gradient y = x^3 + 2x^2 + 5x + 1

Hãy tính dy/dx tại giá trị của x?

Dùng phương pháp Gradient Descent với Learning Rate alpha = 0.1 để cập nhập giá trị x trong 10 vòng lặp

In [1]:
import torch

x = torch.tensor(2.0, requires_grad=True)
alpha = 0.1
epochs = 10

print(f"Giá trị ban đầu: x = {x.item():.4f}")
print("-" * 30)

for epoch in range(epochs):
    y = x**3 + 2*x**2 + 5*x + 1
    
    if x.grad is not None:
        x.grad.zero_()
        
    y.backward()
    
    current_grad = x.grad.item()
    
    with torch.no_grad():
        x -= alpha * x.grad
        
    print(f"Vòng lặp {epoch+1}: dy/dx = {current_grad:>7.2f} | x mới = {x.item():.4f}")

print("-" * 30)
print(f"Giá trị x cuối cùng sau 10 vòng lặp: {x.item():.4f}")

Giá trị ban đầu: x = 2.0000
------------------------------
Vòng lặp 1: dy/dx =   25.00 | x mới = -0.5000
Vòng lặp 2: dy/dx =    3.75 | x mới = -0.8750
Vòng lặp 3: dy/dx =    3.80 | x mới = -1.2547
Vòng lặp 4: dy/dx =    4.70 | x mới = -1.7251
Vòng lặp 5: dy/dx =    7.03 | x mới = -2.4278
Vòng lặp 6: dy/dx =   12.97 | x mới = -3.7250
Vòng lặp 7: dy/dx =   31.73 | x mới = -6.8977
Vòng lặp 8: dy/dx =  120.14 | x mới = -18.9120
Vòng lặp 9: dy/dx = 1002.34 | x mới = -119.1464
Vòng lặp 10: dy/dx = 42116.01 | x mới = -4330.7476
------------------------------
Giá trị x cuối cùng sau 10 vòng lặp: -4330.7476


## Bài 3
Tạo một tập dữ liệu giả lập với x là số giờ học ngẫu nhiên từ 1 đến 10 và y là số điểm được tính theo công thức: y = 3x + 5 + noise (với noise là một giá trị ngẫu nhiên nhỏ).

1. Khởi tạo tham số w và b ngẫu nhiên với requires_grad = True.
2. Tính MSE.
3. Tính gradient.
4. Cập nhật tham số w và b bằng Gradient Descent với Learning Rate alpha = 0.01
5. Lặp lại quá trình trên trong 100 vòng lặp để xem sự hội tụ của mô hình.

In [4]:
import torch

torch.manual_seed(42)

x = torch.linspace(1, 10, 100).reshape(-1, 1)

noise = torch.randn(x.size()) * 1.5
y = 3 * x + 5 + noise

w = torch.randn(1, requires_grad=True)
b = torch.randn(1, requires_grad=True)

alpha = 0.01  
epochs = 100  

print(f"Giá trị khởi tạo: w = {w.item():.4f}, b = {b.item():.4f}")
print("-" * 50)

for epoch in range(epochs):
    y_pred = x * w + b

    mse_loss = torch.mean((y_pred - y)**2)
    
    mse_loss.backward()
    
    with torch.no_grad():
        w -= alpha * w.grad
        b -= alpha * b.grad
        
        w.grad.zero_()
        b.grad.zero_()
    
    if (epoch + 1) % 10 == 0:
        print(f"Vòng lặp {epoch+1:3d} | MSE: {mse_loss.item():.4f} | w: {w.item():.4f} | b: {b.item():.4f}")

print("-" * 50)
print(f"KẾT QUẢ CUỐI CÙNG:")
print(f"MSE cuối cùng: {mse_loss.item():.4f}")
print(f"Công thức học được: y = {w.item():.4f}x + {b.item():.4f}")

Giá trị khởi tạo: w = -0.5672, b = -0.5706
--------------------------------------------------
Vòng lặp  10 | MSE: 6.6361 | w: 3.7182 | b: 0.2522
Vòng lặp  20 | MSE: 6.3227 | w: 3.6922 | b: 0.4269
Vòng lặp  30 | MSE: 6.0312 | w: 3.6671 | b: 0.5953
Vòng lặp  40 | MSE: 5.7602 | w: 3.6430 | b: 0.7576
Vòng lặp  50 | MSE: 5.5082 | w: 3.6196 | b: 0.9142
Vòng lặp  60 | MSE: 5.2739 | w: 3.5972 | b: 1.0652
Vòng lặp  70 | MSE: 5.0560 | w: 3.5755 | b: 1.2108
Vòng lặp  80 | MSE: 4.8533 | w: 3.5546 | b: 1.3512
Vòng lặp  90 | MSE: 4.6649 | w: 3.5345 | b: 1.4866
Vòng lặp 100 | MSE: 4.4897 | w: 3.5150 | b: 1.6172
--------------------------------------------------
KẾT QUẢ CUỐI CÙNG:
MSE cuối cùng: 4.4897
Công thức học được: y = 3.5150x + 1.6172


## Pytorch with Tensor

In [7]:
import torch
import numpy as np


In [8]:
torch.__version__

'2.6.0'

In [9]:
# Chuyển đổi mảng mumpy sang tensor pytorch

arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(arr.dtype)
print(type(arr))

[1 2 3 4 5]
int64
<class 'numpy.ndarray'>


In [10]:
X = torch.from_numpy(arr)
print(X)
print(X.dtype)

tensor([1, 2, 3, 4, 5])
torch.int64


In [11]:
print(x.type())

torch.FloatTensor


In [12]:
arr2 = np.arange(0., 12.).reshape(4, 3)
arr2

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [21]:
x2 = torch.from_numpy(arr2)
print(x2)
print(x2.type())

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)
torch.DoubleTensor


In [22]:
# copy and sharing

x = torch.from_numpy(arr)
print(x)



tensor([99,  1,  2,  3,  4])


In [23]:
arr[0] = 99
print(x)

tensor([99,  1,  2,  3,  4])


In [16]:
arr = np.arange(0, 5)
x = torch.tensor(arr)
print(x)

tensor([0, 1, 2, 3, 4])


In [17]:
arr[0] = 99
print(x)

tensor([0, 1, 2, 3, 4])


# BTVN

## Bài 4
Giải thích 2 trường hợp trên

## Trường hợp 1

torch.from_numpy(arr) dùng chung bộ nhớ. Pytorch không tạo ra bản sao mới của dữ liệu mà nó tạo ra một tensor đưa thẳng vào bộ nhớ mà mảng Numpy đang sử dụng.

arr ban đầu: [0, 1, 2, 3, 4] --> x: [0, 1, 2, 3, 4]

arr[0] = 99 --> x sẽ là: [99, 1, 2, 3, 4]

## Trường hợp 2

torch.tensor(arr) sao chép dữ liệu. Pytorch sẽ thực hiện copy dữ liệu từ Numpy sang một vùng bộ nhớ mới hoàn toàn do Pytorch quản lý.

arr ban đầu: [0, 1, 2, 3, 4] --> x: [0, 1, 2, 3, 4]

arr[0] = 99 --> x sẽ là: [0, 1, 2, 3, 4]

## Bài 5

Bạn giúp thầy tạo tensor với:

empty

zeros

ones

random

Reshape với view và view as

In [ ]:
import torch

empty_tensor = torch.empty(2, 3) 

zeros_tensor = torch.zeros(2, 3)

ones_tensor = torch.ones(2, 3)

rand_tensor = torch.rand(2, 3)

print(f"Empty:\n{empty_tensor}")
print(f"Zeros:\n{zeros_tensor}")
print(f"Ones:\n{ones_tensor}")
print(f"Random:\n{rand_tensor}")

Empty:
tensor([[0., 0., 0.],
        [0., 0., 0.]])
Zeros:
tensor([[0., 0., 0.],
        [0., 0., 0.]])
Ones:
tensor([[1., 1., 1.],
        [1., 1., 1.]])
Random:
tensor([[0.5014, 0.3139, 0.4654],
        [0.1612, 0.1568, 0.2083]])


In [ ]:
x = torch.randn(4, 4) 

y = x.view(2, 8)

z = x.view(-1, 16) 

print(f"Hình dạng gốc: {x.shape}")
print(f"Hình dạng sau view(2, 8): {y.shape}")
print(f"Hình dạng sau view(-1, 16): {z.shape}")

Hình dạng gốc: torch.Size([4, 4])
Hình dạng sau view(2, 8): torch.Size([2, 8])
Hình dạng sau view(-1, 16): torch.Size([1, 16])


In [ ]:
A = torch.zeros(16)      
B = torch.randn(4, 4)    

C = A.view_as(B)

print(f"Hình dạng của C: {C.shape}") 

Hình dạng của C: torch.Size([4, 4])
