# DEEP LEARNING

## WEEK 2: Numpy, Pandas, Matplotlib

## NUMPY

In [3]:
%pip install numpy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 2.0 MB/s  0:00:02 eta 0:00:01
Note: you may need to restart the kernel to use updated packages.


In [17]:
# Numpy là thư viện kiểu list
# vì:
#+ numpy nhanh
#+ có nhiều hàm tích hợp dễ sử dụng cho AI

# để sử dụng numpy thì: pip install numpy

import numpy as np

In [18]:
# thử tạo một danh sách

python_list = [1, 2, 3]

# chuyển đổi danh sách trên thành numpy list 

numpy_list = np.array(python_list)

type(numpy_list)

numpy.ndarray

In [19]:
# list trong python có thể hỗ trợ nhiều loại dữ liệu trong list

my_list = [1, "chao", True, 3.6]

In [20]:
my_list = [1, 2, 3, 4.5]
np_list = np.array(my_list)
np_list

array([1. , 2. , 3. , 4.5])

In [21]:
# chuyển đổi kiểu dữ liệu thì sao?

np_list_int = np_list.astype(np.int32)
np_list_int

array([1, 2, 3, 4], dtype=int32)

In [22]:
# accessing và indexing

x = np.array([1, 2, 3, 4, 5, 6, 7, 8]) # x = np.array(range(1, 9))

In [23]:
# lấy số 4

x[3]

np.int64(4)

In [24]:
# lấy nhiều hơn 1 phần tử
# công thức: array[start:end:step]
# Lấy 1, 2, 3

x[0:3]

array([1, 2, 3])

In [25]:
# lấy từ 3 đến 8 theo 3 cách
# cách 1
x[2:8]


array([3, 4, 5, 6, 7, 8])

In [26]:
# cách 2
x[2:]

array([3, 4, 5, 6, 7, 8])

In [27]:
# cách 3: không đúng
x[2:-1]

array([3, 4, 5, 6, 7])

In [28]:
# lấy số 3 và 5
x[2], x[4]

(np.int64(3), np.int64(5))

In [29]:
# đặt danh sách các index muốn truy cập

x[[2, 4]]

array([3, 5])

In [30]:
data = [[1, 2], [3, 4], [5, 6]]
np_list = np.array(data)
np_list

array([[1, 2],
       [3, 4],
       [5, 6]])

In [31]:
# lấy số 2
np_list[0, 1]  

np.int64(2)

In [32]:
# lấy số 6
np_list[2, 1]

np.int64(6)

In [33]:
# lấy [3, 4], [5, 6]
# cách 1
np_list[1:,:]

array([[3, 4],
       [5, 6]])

In [34]:
# cách 2
np_list[1:]

array([[3, 4],
       [5, 6]])

In [35]:
# cách 3
np_list[-2:]

array([[3, 4],
       [5, 6]])

In [36]:
# lấy 1, 3, 5
np_list[:,0]

array([1, 3, 5])

In [37]:
# lấy 1 và 5 
# cách 1
np_list[[0,2],0]

array([1, 5])

In [38]:
# cách 2
np_list[0::2, 0]


array([1, 5])

In [39]:
x = [
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
]

np_list = np.array(x)
np_list

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [40]:
# lấy 2 6 10 14
np_list[:,1]

array([ 2,  6, 10, 14])

In [41]:
# lấy 7 và 11
np_list[[1, 2], 2]

array([ 7, 11])

In [42]:
# lấy 4, 7, 10
np_list[[0, 1, 2], [3, 2, 1]]

array([ 4,  7, 10])

In [43]:
# lấy 16, 15, 14, 13
# cách 1
np_list[3, ::-1]

array([16, 15, 14, 13])

In [44]:
# cách 2
np_list[[3, 3, 3, 3], [3, 2, 1, 0]]

array([16, 15, 14, 13])

## BTVN

### Bài 1: 
Cho ma trận = [[99, 99, 99]

               [99, 99, 99]
               
               [99, 99, 99]]

Hãy tưởng tượng ô 99 trống

Giả sử 1 là x, 0 là o

Lấy đầu vào từ phía x và phía o luân phiên.

Nếu đầu vào từ phía x là (0, 0) thì ma trận sẽ trở thành 

               [[x, 99, 99]

               [99, 99, 99]
               
               [99, 99, 99]]

Nếu đầu vào từ phía o cũng là (0, 0) 

Thông báo họ nhập lại, nếu không thì điền vào ma trận.

Thử thách: Nếu người đầu tiên có 3 phần tử liên tiếp thì dừng chơi.

In [64]:
import numpy as np

# Khởi tạo bàn cờ
board = np.full((3, 3), 99)

def print_board():
    print(board)
    print()

def check_win(player):
    # Kiểm tra hàng
    if np.any(np.all(board == player, axis=1)):
        return True

    # Kiểm tra cột
    if np.any(np.all(board == player, axis=0)):
        return True

    # Kiểm tra đường chéo
    if np.all(np.diag(board) == player):
        return True
    if np.all(np.diag(np.fliplr(board)) == player):
        return True

    return False


current_player = 1  

while True:
    print_board()
    symbol = "x" if current_player == 1 else "o"
    print(f"Lượt của {symbol}")

    row = int(input("Nhập row (0-2): "))
    col = int(input("Nhập col (0-2): "))

    # Kiểm tra ô trống
    if board[row, col] != 99:
        print("Ô đã được chọn, vui lòng nhập lại!\n")
        continue

    # Điền vào ma trận
    board[row, col] = current_player

    # Kiểm tra thắng
    if check_win(current_player):
        print_board()
        print(f"{symbol.upper()} chiến thắng")
        break

    # Đổi lượt
    current_player = 0 if current_player == 1 else 1


[[99 99 99]
 [99 99 99]
 [99 99 99]]

Lượt của x
[[ 1 99 99]
 [99 99 99]
 [99 99 99]]

Lượt của o
[[ 1 99  0]
 [99 99 99]
 [99 99 99]]

Lượt của x
[[ 1 99  0]
 [99  1 99]
 [99 99 99]]

Lượt của o
[[ 1  0  0]
 [99  1 99]
 [99 99 99]]

Lượt của x
[[ 1  0  0]
 [99  1 99]
 [99 99  1]]

X chiến thắng


### Bài 2: 
Cho y = [
    
    [1, 2, 3],

    [4, 5, 6],
    
    [7, 8, 9]
]

1. Lấy 4, 5, 6
2. Lấy 2, 5
3. Lấy 3, 4
4. Lấy 9, 6, 3

In [46]:
y = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
np_l = np.array(y)
np_l

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# Lấy 4, 5, 6
np_l[1, :]

array([4, 5, 6])

In [47]:
# Lấy 2, 5
np_l[[0, 1], 1]

array([2, 5])

In [48]:
# Lấy 3, 4
np_l[[0, 1], [2, 0]]

array([3, 4])

In [50]:
# Lấy 9, 6, 3
np_l[[2, 1, 0], [2, 2, 2]]

array([9, 6, 3])

### Bài 3:
Cho x = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

1. Xuất ra các giá trị chẵn theo sử dụng if
2. Xuất ra các giá trị sử dụng list comprehension

In [60]:
import numpy as np
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) 

# 1. Xuất ra các giá trị chẵn theo sử dụng if
so_chan = []
for num in x:
    if num % 2 == 0:
        so_chan.append(num)
so_chan

[np.int64(2), np.int64(4), np.int64(6), np.int64(8), np.int64(10)]

In [59]:
# 2. Xuất ra các giá trị sử dụng list comprehension
so_chan_lc = [num for num in x if num % 2 == 0]
so_chan_lc

[np.int64(2), np.int64(4), np.int64(6), np.int64(8), np.int64(10)]

In [81]:
np_x = np.arange(10)
np_x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
np_x[np_x%2 == 0]

array([0, 2, 4, 6, 8])

In [83]:
np_x % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [84]:
np_x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [85]:
idx = [ True, True,  True, False,  True, True,  True, False,  True, False]
np_x[idx]

array([0, 1, 2, 4, 5, 6, 8])

In [86]:
np_x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [90]:
cond1 = np_x % 2 != 0
cond2 = np_x < 5
cond3 = np_x > 0

np_x[cond1 & cond2 | cond3]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### Bài 4:
Tạo một mảng numpy có kích thước 150 x 5. Giả sử mẫu này chứa 150 mẫu dữ liệu của sinh viên bao gồm chiều cao, cân nặng, tuổi, lương và điểm trung bình.

Tách mảng dựa trên 4 cột đầu tiên thành một biến có tên là x và cột cuối cùng thành y.

Tách mảng x thành x_train và x_test, trong đó x_train chứa 70% dữ liệu và tách y thành y_train và y_test, trong đó y_train chứa 70% dữ liệu.

Tạo 10 tập dữ liệu x_train không chồng chéo nhau

In [ ]:
import numpy as np

# 1. Tạo dữ liệu 150 x 5
np.random.seed(42)
data = np.random.rand(150, 5)

# 2. Tách x và y
x = data[:, :4] # 4 cột đầu
y = data[:, 4] # cột cuối

# 3. Chia train / test (70% - 30%)
n_samples = x.shape[0]
train_size = int(0.7 * n_samples)

indices = np.random.permutation(n_samples)

train_idx = indices[:train_size]
test_idx  = indices[train_size:]

x_train = x[train_idx]
x_test  = x[test_idx]

y_train = y[train_idx]
y_test  = y[test_idx]

# 4. Tạo 10 tập x_train không chồng chéo
x_train_splits = np.array_split(x_train, 10)

print("x shape:", x.shape)
print("y shape:", y.shape)

print("x_train shape:", x_train.shape)
print("x_test shape:", x_test.shape)

for i, part in enumerate(x_train_splits):
    print(f"x_train_split {i+1}: {part.shape}")


x shape: (150, 4)
y shape: (150,)
x_train shape: (105, 4)
x_test shape: (45, 4)
x_train_split 1: (11, 4)
x_train_split 2: (11, 4)
x_train_split 3: (11, 4)
x_train_split 4: (11, 4)
x_train_split 5: (11, 4)
x_train_split 6: (10, 4)
x_train_split 7: (10, 4)
x_train_split 8: (10, 4)
x_train_split 9: (10, 4)
x_train_split 10: (10, 4)
